apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: image-updater
  template:
    metadata:
      labels:
        app: image-updater
    spec:
      containers:
        - image: akshaykkdocker623/frontend:v1.1
          name: image-updater
          ports:
            - containerPort: 80
