name: checkout-test-build

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: self-hosted
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          

      - name: Install dependencies and test
        run: |
          npm install
          CI=true npm test
          
  
 # docker login and push:
 #   runs-on: self-hosted
 #   steps:
 #     - name: docker login
 #       uses: docker/login-actions@v4
 #       with:
 #         username:
 #         password:
