name: checkout-test-build

on:
  push:
    branches:
      - main
  workflow_dispatch: 
env:
  AWS_REGION: us-east-1

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          

      - name: Install dependencies and test
        run: |
          npm install
          CI=true npm test
          npm run build
          pwd
          ls -la
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build-file
          path: build/
          retention-days: 1
  
  docker_login_and_push:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v3
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build-files
          path: build/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secrete-key-id: ${{ secrets.AWS_SCRETE_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to ecr
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and push to ecr
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/namespace1/repo1:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/namespace1/repo1:latest        
        



          
